language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install python-catkin-pkg python-rosdep
  - sudo rosdep init
  - rosdep update
  - rosdep install --from-paths . --ignore-src --rosdistro groovy -y

before_script:
  - cd /home/travis/build/ros-perception/perception_pcl && git clone https://github.com/ros-perception/pcl_msgs.git
  - cd /home/travis/build/ros-perception/perception_pcl && git clone https://github.com/ros-perception/pcl_conversions.git

script:
  - source /opt/ros/groovy/setup.bash
  - catkin_make_isolated
